export const AccountsABI = [
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "hasAuthorizedValidatorSigner",
        inputs: [{ type: "address", name: "account" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "authorizeValidatorSignerWithPublicKey",
        inputs: [
            { type: "address", name: "signer" },
            { type: "uint8", name: "v" },
            { type: "bytes32", name: "r" },
            { type: "bytes32", name: "s" },
            { type: "bytes", name: "ecdsaPublicKey" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setAccountDataEncryptionKey",
        inputs: [{ type: "bytes", name: "dataEncryptionKey" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "removeVoteSigner",
        inputs: [],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "authorizeValidatorSignerWithKeys",
        inputs: [
            { type: "address", name: "signer" },
            { type: "uint8", name: "v" },
            { type: "bytes32", name: "r" },
            { type: "bytes32", name: "s" },
            { type: "bytes", name: "ecdsaPublicKey" },
            { type: "bytes", name: "blsPublicKey" },
            { type: "bytes", name: "blsPop" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "initialized",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "getWalletAddress",
        inputs: [{ type: "address", name: "account" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "isAccount",
        inputs: [{ type: "address", name: "account" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "getVoteSigner",
        inputs: [{ type: "address", name: "account" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "authorizeVoteSigner",
        inputs: [
            { type: "address", name: "signer" },
            { type: "uint8", name: "v" },
            { type: "bytes32", name: "r" },
            { type: "bytes32", name: "s" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "isAuthorizedSigner",
        inputs: [{ type: "address", name: "signer" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "getValidatorSigner",
        inputs: [{ type: "address", name: "account" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "string", name: "" }],
        name: "getName",
        inputs: [{ type: "address", name: "account" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "hasAuthorizedVoteSigner",
        inputs: [{ type: "address", name: "account" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "getAttestationSigner",
        inputs: [{ type: "address", name: "account" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "validatorSignerToAccount",
        inputs: [{ type: "address", name: "signer" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "voteSignerToAccount",
        inputs: [{ type: "address", name: "signer" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "renounceOwnership",
        inputs: [],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setMetadataURL",
        inputs: [{ type: "string", name: "metadataURL" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "removeAttestationSigner",
        inputs: [],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "authorizeAttestationSigner",
        inputs: [
            { type: "address", name: "signer" },
            { type: "uint8", name: "v" },
            { type: "bytes32", name: "r" },
            { type: "bytes32", name: "s" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "registry",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "attestationSignerToAccount",
        inputs: [{ type: "address", name: "signer" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [
            { type: "uint256[]", name: "" },
            { type: "bytes", name: "" },
        ],
        name: "batchGetMetadataURL",
        inputs: [{ type: "address[]", name: "accountsToQuery" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "owner",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "isOwner",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setAccount",
        inputs: [
            { type: "string", name: "name" },
            { type: "bytes", name: "dataEncryptionKey" },
            { type: "address", name: "walletAddress" },
            { type: "uint8", name: "v" },
            { type: "bytes32", name: "r" },
            { type: "bytes32", name: "s" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "signerToAccount",
        inputs: [{ type: "address", name: "signer" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setWalletAddress",
        inputs: [
            { type: "address", name: "walletAddress" },
            { type: "uint8", name: "v" },
            { type: "bytes32", name: "r" },
            { type: "bytes32", name: "s" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "createAccount",
        inputs: [],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "removeValidatorSigner",
        inputs: [],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "string", name: "" }],
        name: "getMetadataURL",
        inputs: [{ type: "address", name: "account" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setRegistry",
        inputs: [{ type: "address", name: "registryAddress" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bytes", name: "" }],
        name: "getDataEncryptionKey",
        inputs: [{ type: "address", name: "account" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "authorizedBy",
        inputs: [{ type: "address", name: "" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "authorizeValidatorSigner",
        inputs: [
            { type: "address", name: "signer" },
            { type: "uint8", name: "v" },
            { type: "bytes32", name: "r" },
            { type: "bytes32", name: "s" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "hasAuthorizedAttestationSigner",
        inputs: [{ type: "address", name: "account" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setName",
        inputs: [{ type: "string", name: "name" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "initialize",
        inputs: [{ type: "address", name: "registryAddress" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "transferOwnership",
        inputs: [{ type: "address", name: "newOwner" }],
        constant: false,
    },
    {
        type: "event",
        name: "AttestationSignerAuthorized",
        inputs: [
            { type: "address", name: "account", indexed: true },
            { type: "address", name: "signer", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "VoteSignerAuthorized",
        inputs: [
            { type: "address", name: "account", indexed: true },
            { type: "address", name: "signer", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ValidatorSignerAuthorized",
        inputs: [
            { type: "address", name: "account", indexed: true },
            { type: "address", name: "signer", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "AttestationSignerRemoved",
        inputs: [
            { type: "address", name: "account", indexed: true },
            { type: "address", name: "oldSigner", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "VoteSignerRemoved",
        inputs: [
            { type: "address", name: "account", indexed: true },
            { type: "address", name: "oldSigner", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ValidatorSignerRemoved",
        inputs: [
            { type: "address", name: "account", indexed: true },
            { type: "address", name: "oldSigner", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "AccountDataEncryptionKeySet",
        inputs: [
            { type: "address", name: "account", indexed: true },
            { type: "bytes", name: "dataEncryptionKey", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "AccountNameSet",
        inputs: [
            { type: "address", name: "account", indexed: true },
            { type: "string", name: "name", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "AccountMetadataURLSet",
        inputs: [
            { type: "address", name: "account", indexed: true },
            { type: "string", name: "metadataURL", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "AccountWalletAddressSet",
        inputs: [
            { type: "address", name: "account", indexed: true },
            { type: "address", name: "walletAddress", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "AccountCreated",
        inputs: [{ type: "address", name: "account", indexed: true }],
        anonymous: false,
    },
    {
        type: "event",
        name: "RegistrySet",
        inputs: [{ type: "address", name: "registryAddress", indexed: true }],
        anonymous: false,
    },
    {
        type: "event",
        name: "OwnershipTransferred",
        inputs: [
            { type: "address", name: "previousOwner", indexed: true },
            { type: "address", name: "newOwner", indexed: true },
        ],
        anonymous: false,
    },
];
