
export const AttestationsABI = [
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address[]", name: "" }],
        name: "lookupAccountsForIdentifier",
        inputs: [{ type: "bytes32", name: "identifier" }],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "validatorSignerAddressFromCurrentSet",
        inputs: [{ type: "uint256", name: "index" }],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "initialized",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "checkProofOfPossession",
        inputs: [
          { type: "address", name: "sender" },
          { type: "bytes", name: "blsKey" },
          { type: "bytes", name: "blsPop" },
        ],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getEpochNumberOfBlock",
        inputs: [{ type: "uint256", name: "blockNumber" }],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bytes32", name: "" }],
        name: "getVerifiedSealBitmapFromHeader",
        inputs: [{ type: "bytes", name: "header" }],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [
          { type: "uint32[]", name: "" },
          { type: "address[]", name: "" },
          { type: "uint256[]", name: "" },
          { type: "bytes", name: "" },
        ],
        name: "getCompletableAttestations",
        inputs: [
          { type: "bytes32", name: "identifier" },
          { type: "address", name: "account" },
        ],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "withdraw",
        inputs: [{ type: "address", name: "token" }],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [
          { type: "uint32", name: "" },
          { type: "uint32", name: "" },
        ],
        name: "getAttestationStats",
        inputs: [
          { type: "bytes32", name: "identifier" },
          { type: "address", name: "account" },
        ],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "validateAttestationCode",
        inputs: [
          { type: "bytes32", name: "identifier" },
          { type: "address", name: "account" },
          { type: "uint8", name: "v" },
          { type: "bytes32", name: "r" },
          { type: "bytes32", name: "s" },
        ],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "validatorSignerAddressFromSet",
        inputs: [
          { type: "uint256", name: "index" },
          { type: "uint256", name: "blockNumber" },
        ],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address[]", name: "" }],
        name: "getAttestationIssuers",
        inputs: [
          { type: "bytes32", name: "identifier" },
          { type: "address", name: "account" },
        ],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getAttestationRequestFee",
        inputs: [{ type: "address", name: "token" }],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bytes32", name: "" }],
        name: "hashHeader",
        inputs: [{ type: "bytes", name: "header" }],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "renounceOwnership",
        inputs: [],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "minQuorumSizeInCurrentSet",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getMaxAttestations",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "registry",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "maxAttestations",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "numberValidatorsInCurrentSet",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "selectIssuersWaitBlocks",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getBlockNumberFromHeader",
        inputs: [{ type: "bytes", name: "header" }],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "owner",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "isOwner",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [
          { type: "uint256[]", name: "" },
          { type: "address[]", name: "" },
          { type: "uint64[]", name: "" },
          { type: "uint64[]", name: "" },
        ],
        name: "batchGetAttestationStats",
        inputs: [{ type: "bytes32[]", name: "identifiersToLookup" }],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getEpochNumber",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "numberValidatorsInSet",
        inputs: [{ type: "uint256", name: "blockNumber" }],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setAttestationExpiryBlocks",
        inputs: [{ type: "uint256", name: "_attestationExpiryBlocks" }],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setRegistry",
        inputs: [{ type: "address", name: "registryAddress" }],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "attestationExpiryBlocks",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [
          { type: "uint8", name: "" },
          { type: "uint32", name: "" },
          { type: "address", name: "" },
        ],
        name: "getAttestationState",
        inputs: [
          { type: "bytes32", name: "identifier" },
          { type: "address", name: "account" },
          { type: "address", name: "issuer" },
        ],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "revoke",
        inputs: [
          { type: "bytes32", name: "identifier" },
          { type: "uint256", name: "index" },
        ],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "attestationRequestFees",
        inputs: [{ type: "address", name: "" }],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setMaxAttestations",
        inputs: [{ type: "uint256", name: "_maxAttestations" }],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "request",
        inputs: [
          { type: "bytes32", name: "identifier" },
          { type: "uint256", name: "attestationsRequested" },
          { type: "address", name: "attestationRequestFeeToken" },
        ],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getEpochSize",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setSelectIssuersWaitBlocks",
        inputs: [{ type: "uint256", name: "_selectIssuersWaitBlocks" }],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "selectIssuers",
        inputs: [{ type: "bytes32", name: "identifier" }],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [
          { type: "uint32", name: "" },
          { type: "uint32", name: "" },
          { type: "address", name: "" },
        ],
        name: "getUnselectedRequest",
        inputs: [
          { type: "bytes32", name: "identifier" },
          { type: "address", name: "account" },
        ],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "minQuorumSize",
        inputs: [{ type: "uint256", name: "blockNumber" }],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "pendingWithdrawals",
        inputs: [
          { type: "address", name: "" },
          { type: "address", name: "" },
        ],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [
          { type: "uint256", name: "" },
          { type: "uint256", name: "" },
        ],
        name: "fractionMulExp",
        inputs: [
          { type: "uint256", name: "aNumerator" },
          { type: "uint256", name: "aDenominator" },
          { type: "uint256", name: "bNumerator" },
          { type: "uint256", name: "bDenominator" },
          { type: "uint256", name: "exponent" },
          { type: "uint256", name: "_decimals" },
        ],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "transferOwnership",
        inputs: [{ type: "address", name: "newOwner" }],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setAttestationRequestFee",
        inputs: [
          { type: "address", name: "token" },
          { type: "uint256", name: "fee" },
        ],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bytes32", name: "" }],
        name: "getParentSealBitmap",
        inputs: [{ type: "uint256", name: "blockNumber" }],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "complete",
        inputs: [
          { type: "bytes32", name: "identifier" },
          { type: "uint8", name: "v" },
          { type: "bytes32", name: "r" },
          { type: "bytes32", name: "s" },
        ],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "initialize",
        inputs: [
          { type: "address", name: "registryAddress" },
          { type: "uint256", name: "_attestationExpiryBlocks" },
          { type: "uint256", name: "_selectIssuersWaitBlocks" },
          { type: "uint256", name: "_maxAttestations" },
          { type: "address[]", name: "attestationRequestFeeTokens" },
          { type: "uint256[]", name: "attestationRequestFeeValues" },
        ],
        constant: false,
      },
      {
        type: "event",
        name: "AttestationsRequested",
        inputs: [
          { type: "bytes32", name: "identifier", indexed: true },
          { type: "address", name: "account", indexed: true },
          { type: "uint256", name: "attestationsRequested", indexed: false },
          {
            type: "address",
            name: "attestationRequestFeeToken",
            indexed: false,
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "AttestationIssuerSelected",
        inputs: [
          { type: "bytes32", name: "identifier", indexed: true },
          { type: "address", name: "account", indexed: true },
          { type: "address", name: "issuer", indexed: true },
          {
            type: "address",
            name: "attestationRequestFeeToken",
            indexed: false,
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "AttestationCompleted",
        inputs: [
          { type: "bytes32", name: "identifier", indexed: true },
          { type: "address", name: "account", indexed: true },
          { type: "address", name: "issuer", indexed: true },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "Withdrawal",
        inputs: [
          { type: "address", name: "account", indexed: true },
          { type: "address", name: "token", indexed: true },
          { type: "uint256", name: "amount", indexed: false },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "AttestationExpiryBlocksSet",
        inputs: [{ type: "uint256", name: "value", indexed: false }],
        anonymous: false,
      },
      {
        type: "event",
        name: "AttestationRequestFeeSet",
        inputs: [
          { type: "address", name: "token", indexed: true },
          { type: "uint256", name: "value", indexed: false },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "SelectIssuersWaitBlocksSet",
        inputs: [{ type: "uint256", name: "value", indexed: false }],
        anonymous: false,
      },
      {
        type: "event",
        name: "MaxAttestationsSet",
        inputs: [{ type: "uint256", name: "value", indexed: false }],
        anonymous: false,
      },
      {
        type: "event",
        name: "RegistrySet",
        inputs: [{ type: "address", name: "registryAddress", indexed: true }],
        anonymous: false,
      },
      {
        type: "event",
        name: "OwnershipTransferred",
        inputs: [
          { type: "address", name: "previousOwner", indexed: true },
          { type: "address", name: "newOwner", indexed: true },
        ],
        anonymous: false,
      },
    ];