
export const EscrowABI = [
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "initialized",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address[]", name: "" }],
        name: "getSentPaymentIds",
        inputs: [{ type: "address", name: "sender" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "withdraw",
        inputs: [
            { type: "address", name: "paymentId" },
            { type: "uint8", name: "v" },
            { type: "bytes32", name: "r" },
            { type: "bytes32", name: "s" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address[]", name: "" }],
        name: "getReceivedPaymentIds",
        inputs: [{ type: "bytes32", name: "identifier" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [
            { type: "bytes32", name: "recipientIdentifier" },
            { type: "address", name: "sender" },
            { type: "address", name: "token" },
            { type: "uint256", name: "value" },
            { type: "uint256", name: "sentIndex" },
            { type: "uint256", name: "receivedIndex" },
            { type: "uint256", name: "timestamp" },
            { type: "uint256", name: "expirySeconds" },
            { type: "uint256", name: "minAttestations" },
        ],
        name: "escrowedPayments",
        inputs: [{ type: "address", name: "" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "transfer",
        inputs: [
            { type: "bytes32", name: "identifier" },
            { type: "address", name: "token" },
            { type: "uint256", name: "value" },
            { type: "uint256", name: "expirySeconds" },
            { type: "address", name: "paymentId" },
            { type: "uint256", name: "minAttestations" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "renounceOwnership",
        inputs: [],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "revoke",
        inputs: [{ type: "address", name: "paymentId" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "registry",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "owner",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "isOwner",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "receivedPaymentIds",
        inputs: [
            { type: "bytes32", name: "" },
            { type: "uint256", name: "" },
        ],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setRegistry",
        inputs: [{ type: "address", name: "registryAddress" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "initialize",
        inputs: [{ type: "address", name: "registryAddress" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "sentPaymentIds",
        inputs: [
            { type: "address", name: "" },
            { type: "uint256", name: "" },
        ],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "transferOwnership",
        inputs: [{ type: "address", name: "newOwner" }],
        constant: false,
    },
    {
        type: "event",
        name: "Transfer",
        inputs: [
            { type: "address", name: "from", indexed: true },
            { type: "bytes32", name: "identifier", indexed: true },
            { type: "address", name: "token", indexed: true },
            { type: "uint256", name: "value", indexed: false },
            { type: "address", name: "paymentId", indexed: false },
            { type: "uint256", name: "minAttestations", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Withdrawal",
        inputs: [
            { type: "bytes32", name: "identifier", indexed: true },
            { type: "address", name: "to", indexed: true },
            { type: "address", name: "token", indexed: true },
            { type: "uint256", name: "value", indexed: false },
            { type: "address", name: "paymentId", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Revocation",
        inputs: [
            { type: "bytes32", name: "identifier", indexed: true },
            { type: "address", name: "by", indexed: true },
            { type: "address", name: "token", indexed: true },
            { type: "uint256", name: "value", indexed: false },
            { type: "address", name: "paymentId", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RegistrySet",
        inputs: [{ type: "address", name: "registryAddress", indexed: true }],
        anonymous: false,
    },
    {
        type: "event",
        name: "OwnershipTransferred",
        inputs: [
            { type: "address", name: "previousOwner", indexed: true },
            { type: "address", name: "newOwner", indexed: true },
        ],
        anonymous: false,
    },
];