
export const ExchangeABI = [
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "initialized",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "minimumReports",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "stable",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "stableBucket",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "exchange",
        inputs: [
            { type: "uint256", name: "sellAmount" },
            { type: "uint256", name: "minBuyAmount" },
            { type: "bool", name: "sellGold" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setUpdateFrequency",
        inputs: [{ type: "uint256", name: "newUpdateFrequency" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getSellTokenAmount",
        inputs: [
            { type: "uint256", name: "buyAmount" },
            { type: "bool", name: "sellGold" },
        ],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "value" }],
        name: "spread",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "goldBucket",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "updateFrequency",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setReserveFraction",
        inputs: [{ type: "uint256", name: "newReserveFraction" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "renounceOwnership",
        inputs: [],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [
            { type: "uint256", name: "" },
            { type: "uint256", name: "" },
        ],
        name: "getBuyAndSellBuckets",
        inputs: [{ type: "bool", name: "sellGold" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "registry",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "initialize",
        inputs: [
            { type: "address", name: "registryAddress" },
            { type: "address", name: "stableToken" },
            { type: "uint256", name: "_spread" },
            { type: "uint256", name: "_reserveFraction" },
            { type: "uint256", name: "_updateFrequency" },
            { type: "uint256", name: "_minimumReports" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "owner",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "isOwner",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getBuyTokenAmount",
        inputs: [
            { type: "uint256", name: "sellAmount" },
            { type: "bool", name: "sellGold" },
        ],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setRegistry",
        inputs: [{ type: "address", name: "registryAddress" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setSpread",
        inputs: [{ type: "uint256", name: "newSpread" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setMinimumReports",
        inputs: [{ type: "uint256", name: "newMininumReports" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setStableToken",
        inputs: [{ type: "address", name: "newStableToken" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "value" }],
        name: "reserveFraction",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "lastBucketUpdate",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "transferOwnership",
        inputs: [{ type: "address", name: "newOwner" }],
        constant: false,
    },
    {
        type: "event",
        name: "Exchanged",
        inputs: [
            { type: "address", name: "exchanger", indexed: true },
            { type: "uint256", name: "sellAmount", indexed: false },
            { type: "uint256", name: "buyAmount", indexed: false },
            { type: "bool", name: "soldGold", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "UpdateFrequencySet",
        inputs: [{ type: "uint256", name: "updateFrequency", indexed: false }],
        anonymous: false,
    },
    {
        type: "event",
        name: "MinimumReportsSet",
        inputs: [{ type: "uint256", name: "minimumReports", indexed: false }],
        anonymous: false,
    },
    {
        type: "event",
        name: "StableTokenSet",
        inputs: [{ type: "address", name: "stable", indexed: true }],
        anonymous: false,
    },
    {
        type: "event",
        name: "SpreadSet",
        inputs: [{ type: "uint256", name: "spread", indexed: false }],
        anonymous: false,
    },
    {
        type: "event",
        name: "ReserveFractionSet",
        inputs: [{ type: "uint256", name: "reserveFraction", indexed: false }],
        anonymous: false,
    },
    {
        type: "event",
        name: "RegistrySet",
        inputs: [{ type: "address", name: "registryAddress", indexed: true }],
        anonymous: false,
    },
    {
        type: "event",
        name: "OwnershipTransferred",
        inputs: [
            { type: "address", name: "previousOwner", indexed: true },
            { type: "address", name: "newOwner", indexed: true },
        ],
        anonymous: false,
    },
];