export const FeeCurrencyWhitelistABI = [
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "initialized",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "renounceOwnership",
        inputs: [],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "whitelist",
        inputs: [{ type: "uint256", name: "" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "initialize",
        inputs: [],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "owner",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "isOwner",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address[]", name: "" }],
        name: "getWhitelist",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "addToken",
        inputs: [{ type: "address", name: "tokenAddress" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "transferOwnership",
        inputs: [{ type: "address", name: "newOwner" }],
        constant: false,
    },
    {
        type: "event",
        name: "OwnershipTransferred",
        inputs: [
            { type: "address", name: "previousOwner", indexed: true },
            { type: "address", name: "newOwner", indexed: true },
        ],
        anonymous: false,
    },
];