export const GasPriceMinimumABI = [
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "initialized",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setAdjustmentSpeed",
        inputs: [{ type: "uint256", name: "_adjustmentSpeed" }],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "gasPriceMinimum",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "value" }],
        name: "targetDensity",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "initialize",
        inputs: [
          { type: "address", name: "_registryAddress" },
          { type: "uint256", name: "_gasPriceMinimumFloor" },
          { type: "uint256", name: "_targetDensity" },
          { type: "uint256", name: "_adjustmentSpeed" },
        ],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "renounceOwnership",
        inputs: [],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "registry",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "owner",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "isOwner",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setTargetDensity",
        inputs: [{ type: "uint256", name: "_targetDensity" }],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getGasPriceMinimum",
        inputs: [{ type: "address", name: "tokenAddress" }],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "value" }],
        name: "adjustmentSpeed",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setRegistry",
        inputs: [{ type: "address", name: "registryAddress" }],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setGasPriceMinimumFloor",
        inputs: [{ type: "uint256", name: "_gasPriceMinimumFloor" }],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "updateGasPriceMinimum",
        inputs: [
          { type: "uint256", name: "blockGasTotal" },
          { type: "uint256", name: "blockGasLimit" },
        ],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "gasPriceMinimumFloor",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getUpdatedGasPriceMinimum",
        inputs: [
          { type: "uint256", name: "blockGasTotal" },
          { type: "uint256", name: "blockGasLimit" },
        ],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "transferOwnership",
        inputs: [{ type: "address", name: "newOwner" }],
        constant: false,
      },
      {
        type: "event",
        name: "TargetDensitySet",
        inputs: [{ type: "uint256", name: "targetDensity", indexed: false }],
        anonymous: false,
      },
      {
        type: "event",
        name: "GasPriceMinimumFloorSet",
        inputs: [
          { type: "uint256", name: "gasPriceMinimumFloor", indexed: false },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "AdjustmentSpeedSet",
        inputs: [{ type: "uint256", name: "adjustmentSpeed", indexed: false }],
        anonymous: false,
      },
      {
        type: "event",
        name: "GasPriceMinimumUpdated",
        inputs: [{ type: "uint256", name: "gasPriceMinimum", indexed: false }],
        anonymous: false,
      },
      {
        type: "event",
        name: "RegistrySet",
        inputs: [{ type: "address", name: "registryAddress", indexed: true }],
        anonymous: false,
      },
      {
        type: "event",
        name: "OwnershipTransferred",
        inputs: [
          { type: "address", name: "previousOwner", indexed: true },
          { type: "address", name: "newOwner", indexed: true },
        ],
        anonymous: false,
      },
    ];