export const GoldTokenABI = [
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "string", name: "" }],
        name: "name",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "approve",
        inputs: [
            { type: "address", name: "spender" },
            { type: "uint256", name: "value" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "initialized",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "totalSupply",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "transferFrom",
        inputs: [
            { type: "address", name: "from" },
            { type: "address", name: "to" },
            { type: "uint256", name: "value" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint8", name: "" }],
        name: "decimals",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "increaseAllowance",
        inputs: [
            { type: "address", name: "spender" },
            { type: "uint256", name: "value" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "mint",
        inputs: [
            { type: "address", name: "to" },
            { type: "uint256", name: "value" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "balanceOf",
        inputs: [{ type: "address", name: "owner" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "renounceOwnership",
        inputs: [],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "registry",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "owner",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "isOwner",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "string", name: "" }],
        name: "symbol",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "decreaseAllowance",
        inputs: [
            { type: "address", name: "spender" },
            { type: "uint256", name: "value" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "transfer",
        inputs: [
            { type: "address", name: "to" },
            { type: "uint256", name: "value" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setRegistry",
        inputs: [{ type: "address", name: "registryAddress" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "increaseSupply",
        inputs: [{ type: "uint256", name: "amount" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "initialize",
        inputs: [{ type: "address", name: "registryAddress" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "allowance",
        inputs: [
            { type: "address", name: "owner" },
            { type: "address", name: "spender" },
        ],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "transferWithComment",
        inputs: [
            { type: "address", name: "to" },
            { type: "uint256", name: "value" },
            { type: "string", name: "comment" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "transferOwnership",
        inputs: [{ type: "address", name: "newOwner" }],
        constant: false,
    },
    {
        type: "event",
        name: "Transfer",
        inputs: [
            { type: "address", name: "from", indexed: true },
            { type: "address", name: "to", indexed: true },
            { type: "uint256", name: "value", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "TransferComment",
        inputs: [{ type: "string", name: "comment", indexed: false }],
        anonymous: false,
    },
    {
        type: "event",
        name: "Approval",
        inputs: [
            { type: "address", name: "owner", indexed: true },
            { type: "address", name: "spender", indexed: true },
            { type: "uint256", name: "value", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RegistrySet",
        inputs: [{ type: "address", name: "registryAddress", indexed: true }],
        anonymous: false,
    },
    {
        type: "event",
        name: "OwnershipTransferred",
        inputs: [
            { type: "address", name: "previousOwner", indexed: true },
            { type: "address", name: "newOwner", indexed: true },
        ],
        anonymous: false,
    },
];