export const LockedGoldABI = [
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bytes32[]", name: "" }],
        name: "getSlashingWhitelist",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "initialized",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "decrementNonvotingAccountBalance",
        inputs: [
          { type: "address", name: "account" },
          { type: "uint256", name: "value" },
        ],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "removeSlasher",
        inputs: [
          { type: "string", name: "slasherIdentifier" },
          { type: "uint256", name: "index" },
        ],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "unlockingPeriod",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "withdraw",
        inputs: [{ type: "uint256", name: "index" }],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getTotalLockedGold",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getAccountTotalLockedGold",
        inputs: [{ type: "address", name: "account" }],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "slash",
        inputs: [
          { type: "address", name: "account" },
          { type: "uint256", name: "penalty" },
          { type: "address", name: "reporter" },
          { type: "uint256", name: "reward" },
          { type: "address[]", name: "lessers" },
          { type: "address[]", name: "greaters" },
          { type: "uint256[]", name: "indices" },
        ],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getAccountNonvotingLockedGold",
        inputs: [{ type: "address", name: "account" }],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "isSlasher",
        inputs: [{ type: "address", name: "slasher" }],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "unlock",
        inputs: [{ type: "uint256", name: "value" }],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "addSlasher",
        inputs: [{ type: "string", name: "slasherIdentifier" }],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setUnlockingPeriod",
        inputs: [{ type: "uint256", name: "value" }],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bytes32", name: "" }],
        name: "slashingWhitelist",
        inputs: [{ type: "uint256", name: "" }],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "incrementNonvotingAccountBalance",
        inputs: [
          { type: "address", name: "account" },
          { type: "uint256", name: "value" },
        ],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "renounceOwnership",
        inputs: [],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "registry",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getNonvotingLockedGold",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "owner",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "isOwner",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setRegistry",
        inputs: [{ type: "address", name: "registryAddress" }],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "relock",
        inputs: [
          { type: "uint256", name: "index" },
          { type: "uint256", name: "value" },
        ],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getTotalPendingWithdrawals",
        inputs: [{ type: "address", name: "account" }],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "totalNonvoting",
        inputs: [],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "initialize",
        inputs: [
          { type: "address", name: "registryAddress" },
          { type: "uint256", name: "_unlockingPeriod" },
        ],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "transferOwnership",
        inputs: [{ type: "address", name: "newOwner" }],
        constant: false,
      },
      {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [
          { type: "uint256[]", name: "" },
          { type: "uint256[]", name: "" },
        ],
        name: "getPendingWithdrawals",
        inputs: [{ type: "address", name: "account" }],
        constant: true,
      },
      {
        type: "function",
        stateMutability: "payable",
        payable: true,
        outputs: [],
        name: "lock",
        inputs: [],
        constant: false,
      },
      {
        type: "event",
        name: "UnlockingPeriodSet",
        inputs: [{ type: "uint256", name: "period", indexed: false }],
        anonymous: false,
      },
      {
        type: "event",
        name: "GoldLocked",
        inputs: [
          { type: "address", name: "account", indexed: true },
          { type: "uint256", name: "value", indexed: false },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "GoldUnlocked",
        inputs: [
          { type: "address", name: "account", indexed: true },
          { type: "uint256", name: "value", indexed: false },
          { type: "uint256", name: "available", indexed: false },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "GoldWithdrawn",
        inputs: [
          { type: "address", name: "account", indexed: true },
          { type: "uint256", name: "value", indexed: false },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "SlasherWhitelistAdded",
        inputs: [{ type: "string", name: "slasherIdentifier", indexed: true }],
        anonymous: false,
      },
      {
        type: "event",
        name: "SlasherWhitelistRemoved",
        inputs: [{ type: "string", name: "slasherIdentifier", indexed: true }],
        anonymous: false,
      },
      {
        type: "event",
        name: "AccountSlashed",
        inputs: [
          { type: "address", name: "slashed", indexed: true },
          { type: "uint256", name: "penalty", indexed: false },
          { type: "address", name: "reporter", indexed: true },
          { type: "uint256", name: "reward", indexed: false },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "RegistrySet",
        inputs: [{ type: "address", name: "registryAddress", indexed: true }],
        anonymous: false,
      },
      {
        type: "event",
        name: "OwnershipTransferred",
        inputs: [
          { type: "address", name: "previousOwner", indexed: true },
          { type: "address", name: "newOwner", indexed: true },
        ],
        anonymous: false,
      },
    ];