export const ReserveABI = [
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setDailySpendingRatio",
        inputs: [{ type: "uint256", name: "ratio" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "transferExchangeGold",
        inputs: [
            { type: "address", name: "to" },
            { type: "uint256", name: "value" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "frozenReserveGoldStartBalance",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bytes32", name: "" }],
        name: "assetAllocationSymbols",
        inputs: [{ type: "uint256", name: "" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "removeToken",
        inputs: [
            { type: "address", name: "token" },
            { type: "uint256", name: "index" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "initialized",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [
            { type: "uint256", name: "" },
            { type: "uint256", name: "" },
        ],
        name: "getOrComputeTobinTax",
        inputs: [],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "isToken",
        inputs: [{ type: "address", name: "" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "transferGold",
        inputs: [
            { type: "address", name: "to" },
            { type: "uint256", name: "value" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "addOtherReserveAddress",
        inputs: [{ type: "address", name: "reserveAddress" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [
            { type: "uint128", name: "numerator" },
            { type: "uint128", name: "timestamp" },
        ],
        name: "tobinTaxCache",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getFrozenReserveGoldBalance",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "spendingLimit",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "otherReserveAddresses",
        inputs: [{ type: "uint256", name: "" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getReserveRatio",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "removeOtherReserveAddress",
        inputs: [
            { type: "address", name: "reserveAddress" },
            { type: "uint256", name: "index" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "TOBIN_TAX_NUMERATOR",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "frozenReserveGoldDays",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "renounceOwnership",
        inputs: [],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getOtherReserveAddressesGoldBalance",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getDailySpendingRatio",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "registry",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "isOtherReserveAddress",
        inputs: [{ type: "address", name: "" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "frozenReserveGoldStartDay",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bytes32[]", name: "" }],
        name: "getAssetAllocationSymbols",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getUnfrozenReserveGoldBalance",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "removeSpender",
        inputs: [{ type: "address", name: "spender" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getReserveGoldBalance",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "owner",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "isOwner",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "isSpender",
        inputs: [{ type: "address", name: "" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address[]", name: "" }],
        name: "getOtherReserveAddresses",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setTobinTaxStalenessThreshold",
        inputs: [{ type: "uint256", name: "value" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setRegistry",
        inputs: [{ type: "address", name: "registryAddress" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address[]", name: "" }],
        name: "getTokens",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "initialize",
        inputs: [
            { type: "address", name: "registryAddress" },
            { type: "uint256", name: "_tobinTaxStalenessThreshold" },
            { type: "uint256", name: "_spendingRatio" },
            { type: "uint256", name: "_frozenGold" },
            { type: "uint256", name: "_frozenDays" },
            { type: "bytes32[]", name: "_assetAllocationSymbols" },
            { type: "uint256[]", name: "_assetAllocationWeights" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setAssetAllocations",
        inputs: [
            { type: "bytes32[]", name: "symbols" },
            { type: "uint256[]", name: "weights" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "addToken",
        inputs: [{ type: "address", name: "token" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getUnfrozenBalance",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "tobinTaxStalenessThreshold",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256[]", name: "" }],
        name: "getAssetAllocationWeights",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "addSpender",
        inputs: [{ type: "address", name: "spender" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setFrozenGold",
        inputs: [
            { type: "uint256", name: "frozenGold" },
            { type: "uint256", name: "frozenDays" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "assetAllocationWeights",
        inputs: [{ type: "bytes32", name: "" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "transferOwnership",
        inputs: [{ type: "address", name: "newOwner" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "lastSpendingDay",
        inputs: [],
        constant: true,
    },
    { type: "fallback", stateMutability: "payable", payable: true },
    {
        type: "event",
        name: "TobinTaxStalenessThresholdSet",
        inputs: [{ type: "uint256", name: "value", indexed: false }],
        anonymous: false,
    },
    {
        type: "event",
        name: "DailySpendingRatioSet",
        inputs: [{ type: "uint256", name: "ratio", indexed: false }],
        anonymous: false,
    },
    {
        type: "event",
        name: "TokenAdded",
        inputs: [{ type: "address", name: "token", indexed: true }],
        anonymous: false,
    },
    {
        type: "event",
        name: "TokenRemoved",
        inputs: [
            { type: "address", name: "token", indexed: true },
            { type: "uint256", name: "index", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "SpenderAdded",
        inputs: [{ type: "address", name: "spender", indexed: true }],
        anonymous: false,
    },
    {
        type: "event",
        name: "SpenderRemoved",
        inputs: [{ type: "address", name: "spender", indexed: true }],
        anonymous: false,
    },
    {
        type: "event",
        name: "OtherReserveAddressAdded",
        inputs: [
            { type: "address", name: "otherReserveAddress", indexed: true },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "OtherReserveAddressRemoved",
        inputs: [
            { type: "address", name: "otherReserveAddress", indexed: true },
            { type: "uint256", name: "index", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "AssetAllocationSet",
        inputs: [
            { type: "bytes32[]", name: "symbols", indexed: false },
            { type: "uint256[]", name: "weights", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ReserveGoldTransferred",
        inputs: [
            { type: "address", name: "spender", indexed: true },
            { type: "address", name: "to", indexed: true },
            { type: "uint256", name: "value", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RegistrySet",
        inputs: [{ type: "address", name: "registryAddress", indexed: true }],
        anonymous: false,
    },
    {
        type: "event",
        name: "OwnershipTransferred",
        inputs: [
            { type: "address", name: "previousOwner", indexed: true },
            { type: "address", name: "newOwner", indexed: true },
        ],
        anonymous: false,
    },
];