export const SortedOraclesABI = [
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [
            { type: "address[]", name: "" },
            { type: "uint256[]", name: "" },
            { type: "uint8[]", name: "" },
        ],
        name: "getRates",
        inputs: [{ type: "address", name: "token" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "medianTimestamp",
        inputs: [{ type: "address", name: "token" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "initialized",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "isOracle",
        inputs: [
            { type: "address", name: "" },
            { type: "address", name: "" },
        ],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "reportExpirySeconds",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "removeOracle",
        inputs: [
            { type: "address", name: "token" },
            { type: "address", name: "oracleAddress" },
            { type: "uint256", name: "index" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "numTimestamps",
        inputs: [{ type: "address", name: "token" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "renounceOwnership",
        inputs: [],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "report",
        inputs: [
            { type: "address", name: "token" },
            { type: "uint256", name: "value" },
            { type: "address", name: "lesserKey" },
            { type: "address", name: "greaterKey" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "owner",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address[]", name: "" }],
        name: "getOracles",
        inputs: [{ type: "address", name: "token" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "isOwner",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "oracles",
        inputs: [
            { type: "address", name: "" },
            { type: "uint256", name: "" },
        ],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [
            { type: "address[]", name: "" },
            { type: "uint256[]", name: "" },
            { type: "uint8[]", name: "" },
        ],
        name: "getTimestamps",
        inputs: [{ type: "address", name: "token" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "numRates",
        inputs: [{ type: "address", name: "token" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "removeExpiredReports",
        inputs: [
            { type: "address", name: "token" },
            { type: "uint256", name: "n" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setReportExpiry",
        inputs: [{ type: "uint256", name: "_reportExpirySeconds" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [
            { type: "uint256", name: "" },
            { type: "uint256", name: "" },
        ],
        name: "medianRate",
        inputs: [{ type: "address", name: "token" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "addOracle",
        inputs: [
            { type: "address", name: "token" },
            { type: "address", name: "oracleAddress" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "transferOwnership",
        inputs: [{ type: "address", name: "newOwner" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "initialize",
        inputs: [{ type: "uint256", name: "_reportExpirySeconds" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [
            { type: "bool", name: "" },
            { type: "address", name: "" },
        ],
        name: "isOldestReportExpired",
        inputs: [{ type: "address", name: "token" }],
        constant: true,
    },
    {
        type: "event",
        name: "OracleAdded",
        inputs: [
            { type: "address", name: "token", indexed: true },
            { type: "address", name: "oracleAddress", indexed: true },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "OracleRemoved",
        inputs: [
            { type: "address", name: "token", indexed: true },
            { type: "address", name: "oracleAddress", indexed: true },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "OracleReported",
        inputs: [
            { type: "address", name: "token", indexed: true },
            { type: "address", name: "oracle", indexed: true },
            { type: "uint256", name: "timestamp", indexed: false },
            { type: "uint256", name: "value", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "OracleReportRemoved",
        inputs: [
            { type: "address", name: "token", indexed: true },
            { type: "address", name: "oracle", indexed: true },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "MedianUpdated",
        inputs: [
            { type: "address", name: "token", indexed: true },
            { type: "uint256", name: "value", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ReportExpirySet",
        inputs: [{ type: "uint256", name: "reportExpiry", indexed: false }],
        anonymous: false,
    },
    {
        type: "event",
        name: "OwnershipTransferred",
        inputs: [
            { type: "address", name: "previousOwner", indexed: true },
            { type: "address", name: "newOwner", indexed: true },
        ],
        anonymous: false,
    },
];