export const ValidatorsABI = [
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "removeMember",
        inputs: [{ type: "address", name: "validator" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "getMembershipInLastEpoch",
        inputs: [{ type: "address", name: "account" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "validatorSignerAddressFromCurrentSet",
        inputs: [{ type: "uint256", name: "index" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "initialized",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [
            { type: "bytes", name: "ecdsaPublicKey" },
            { type: "bytes", name: "blsPublicKey" },
            { type: "address", name: "affiliation" },
            { type: "uint256", name: "score" },
            { type: "address", name: "signer" },
        ],
        name: "getValidator",
        inputs: [{ type: "address", name: "account" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [
            { type: "uint256", name: "" },
            { type: "uint256", name: "" },
        ],
        name: "getValidatorScoreParameters",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "checkProofOfPossession",
        inputs: [
            { type: "address", name: "sender" },
            { type: "bytes", name: "blsKey" },
            { type: "bytes", name: "blsPop" },
        ],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "addFirstMember",
        inputs: [
            { type: "address", name: "validator" },
            { type: "address", name: "lesser" },
            { type: "address", name: "greater" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [
            { type: "uint256[]", name: "" },
            { type: "address[]", name: "" },
            { type: "uint256", name: "" },
            { type: "uint256", name: "" },
        ],
        name: "getMembershipHistory",
        inputs: [{ type: "address", name: "account" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "slashingMultiplierResetPeriod",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getGroupNumMembers",
        inputs: [{ type: "address", name: "account" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getEpochNumberOfBlock",
        inputs: [{ type: "uint256", name: "blockNumber" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address[]", name: "" }],
        name: "getRegisteredValidatorGroups",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getMaxGroupSize",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bytes32", name: "" }],
        name: "getVerifiedSealBitmapFromHeader",
        inputs: [{ type: "bytes", name: "header" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "membershipHistoryLength",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "updateEcdsaPublicKey",
        inputs: [
            { type: "address", name: "account" },
            { type: "address", name: "signer" },
            { type: "bytes", name: "ecdsaPublicKey" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getNumRegisteredValidators",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "getMembershipInLastEpochFromSigner",
        inputs: [{ type: "address", name: "signer" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "isValidatorGroup",
        inputs: [{ type: "address", name: "account" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "maxGroupSize",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "setGroupLockedGoldRequirements",
        inputs: [
            { type: "uint256", name: "value" },
            { type: "uint256", name: "duration" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "validatorSignerAddressFromSet",
        inputs: [
            { type: "uint256", name: "index" },
            { type: "uint256", name: "blockNumber" },
        ],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "deregisterValidatorGroup",
        inputs: [{ type: "uint256", name: "index" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bytes32", name: "" }],
        name: "hashHeader",
        inputs: [{ type: "bytes", name: "header" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setSlashingMultiplierResetPeriod",
        inputs: [{ type: "uint256", name: "value" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setCommissionUpdateDelay",
        inputs: [{ type: "uint256", name: "delay" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [
            { type: "uint256", name: "" },
            { type: "uint256", name: "" },
        ],
        name: "getGroupLockedGoldRequirements",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256[]", name: "" }],
        name: "getGroupsNumMembers",
        inputs: [{ type: "address[]", name: "accounts" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "updatePublicKeys",
        inputs: [
            { type: "address", name: "account" },
            { type: "address", name: "signer" },
            { type: "bytes", name: "ecdsaPublicKey" },
            { type: "bytes", name: "blsPublicKey" },
            { type: "bytes", name: "blsPop" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "renounceOwnership",
        inputs: [],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "minQuorumSizeInCurrentSet",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "setValidatorLockedGoldRequirements",
        inputs: [
            { type: "uint256", name: "value" },
            { type: "uint256", name: "duration" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "calculateGroupEpochScore",
        inputs: [{ type: "uint256[]", name: "uptimes" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "initialize",
        inputs: [
            { type: "address", name: "registryAddress" },
            { type: "uint256", name: "groupRequirementValue" },
            { type: "uint256", name: "groupRequirementDuration" },
            { type: "uint256", name: "validatorRequirementValue" },
            { type: "uint256", name: "validatorRequirementDuration" },
            { type: "uint256", name: "validatorScoreExponent" },
            { type: "uint256", name: "validatorScoreAdjustmentSpeed" },
            { type: "uint256", name: "_membershipHistoryLength" },
            { type: "uint256", name: "_slashingMultiplierResetPeriod" },
            { type: "uint256", name: "_maxGroupSize" },
            { type: "uint256", name: "_commissionUpdateDelay" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "registry",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setNextCommissionUpdate",
        inputs: [{ type: "uint256", name: "commission" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "numberValidatorsInCurrentSet",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getBlockNumberFromHeader",
        inputs: [{ type: "bytes", name: "header" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "deregisterValidator",
        inputs: [{ type: "uint256", name: "index" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "owner",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address[]", name: "" }],
        name: "getTopGroupValidators",
        inputs: [
            { type: "address", name: "account" },
            { type: "uint256", name: "n" },
        ],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "isOwner",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "calculateEpochScore",
        inputs: [{ type: "uint256", name: "uptime" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "reorderMember",
        inputs: [
            { type: "address", name: "validator" },
            { type: "address", name: "lesserMember" },
            { type: "address", name: "greaterMember" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getEpochNumber",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "numberValidatorsInSet",
        inputs: [{ type: "uint256", name: "blockNumber" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [
            { type: "address[]", name: "" },
            { type: "uint256", name: "" },
            { type: "uint256", name: "" },
            { type: "uint256", name: "" },
            { type: "uint256[]", name: "" },
            { type: "uint256", name: "" },
            { type: "uint256", name: "" },
        ],
        name: "getValidatorGroup",
        inputs: [{ type: "address", name: "account" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "setRegistry",
        inputs: [{ type: "address", name: "registryAddress" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "affiliate",
        inputs: [{ type: "address", name: "group" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bytes", name: "blsPublicKey" }],
        name: "getValidatorBlsPublicKeyFromSigner",
        inputs: [{ type: "address", name: "signer" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "resetSlashingMultiplier",
        inputs: [],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getCommissionUpdateDelay",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [
            { type: "uint256", name: "value" },
            { type: "uint256", name: "duration" },
        ],
        name: "validatorLockedGoldRequirements",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "updateBlsPublicKey",
        inputs: [
            { type: "bytes", name: "blsPublicKey" },
            { type: "bytes", name: "blsPop" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "updateValidatorScoreFromSigner",
        inputs: [
            { type: "address", name: "signer" },
            { type: "uint256", name: "uptime" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [
            { type: "uint256", name: "" },
            { type: "uint256", name: "" },
        ],
        name: "getValidatorLockedGoldRequirements",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "halveSlashingMultiplier",
        inputs: [{ type: "address", name: "account" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "meetsAccountLockedGoldRequirements",
        inputs: [{ type: "address", name: "account" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [
            { type: "uint256", name: "value" },
            { type: "uint256", name: "duration" },
        ],
        name: "groupLockedGoldRequirements",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "addMember",
        inputs: [{ type: "address", name: "validator" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "setValidatorScoreParameters",
        inputs: [
            { type: "uint256", name: "exponent" },
            { type: "uint256", name: "adjustmentSpeed" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address[]", name: "" }],
        name: "getRegisteredValidatorSigners",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "distributeEpochPaymentsFromSigner",
        inputs: [
            { type: "address", name: "signer" },
            { type: "uint256", name: "maxPayment" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address[]", name: "" }],
        name: "getRegisteredValidators",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getValidatorGroupSlashingMultiplier",
        inputs: [{ type: "address", name: "account" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getAccountLockedGoldRequirement",
        inputs: [{ type: "address", name: "account" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "getEpochSize",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "commissionUpdateDelay",
        inputs: [],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "setMaxGroupSize",
        inputs: [{ type: "uint256", name: "size" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "forceDeaffiliateIfValidator",
        inputs: [{ type: "address", name: "validatorAccount" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "uint256", name: "" }],
        name: "minQuorumSize",
        inputs: [{ type: "uint256", name: "blockNumber" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "updateCommission",
        inputs: [],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "registerValidator",
        inputs: [
            { type: "bytes", name: "ecdsaPublicKey" },
            { type: "bytes", name: "blsPublicKey" },
            { type: "bytes", name: "blsPop" },
        ],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "address", name: "" }],
        name: "groupMembershipInEpoch",
        inputs: [
            { type: "address", name: "account" },
            { type: "uint256", name: "epochNumber" },
            { type: "uint256", name: "index" },
        ],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [
            { type: "uint256", name: "" },
            { type: "uint256", name: "" },
        ],
        name: "fractionMulExp",
        inputs: [
            { type: "uint256", name: "aNumerator" },
            { type: "uint256", name: "aDenominator" },
            { type: "uint256", name: "bNumerator" },
            { type: "uint256", name: "bDenominator" },
            { type: "uint256", name: "exponent" },
            { type: "uint256", name: "_decimals" },
        ],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "registerValidatorGroup",
        inputs: [{ type: "uint256", name: "commission" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "setMembershipHistoryLength",
        inputs: [{ type: "uint256", name: "length" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [],
        name: "transferOwnership",
        inputs: [{ type: "address", name: "newOwner" }],
        constant: false,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "isValidator",
        inputs: [{ type: "address", name: "account" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "view",
        payable: false,
        outputs: [{ type: "bytes32", name: "" }],
        name: "getParentSealBitmap",
        inputs: [{ type: "uint256", name: "blockNumber" }],
        constant: true,
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        payable: false,
        outputs: [{ type: "bool", name: "" }],
        name: "deaffiliate",
        inputs: [],
        constant: false,
    },
    {
        type: "event",
        name: "MaxGroupSizeSet",
        inputs: [{ type: "uint256", name: "size", indexed: false }],
        anonymous: false,
    },
    {
        type: "event",
        name: "CommissionUpdateDelaySet",
        inputs: [{ type: "uint256", name: "delay", indexed: false }],
        anonymous: false,
    },
    {
        type: "event",
        name: "ValidatorScoreParametersSet",
        inputs: [
            { type: "uint256", name: "exponent", indexed: false },
            { type: "uint256", name: "adjustmentSpeed", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "GroupLockedGoldRequirementsSet",
        inputs: [
            { type: "uint256", name: "value", indexed: false },
            { type: "uint256", name: "duration", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ValidatorLockedGoldRequirementsSet",
        inputs: [
            { type: "uint256", name: "value", indexed: false },
            { type: "uint256", name: "duration", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "MembershipHistoryLengthSet",
        inputs: [{ type: "uint256", name: "length", indexed: false }],
        anonymous: false,
    },
    {
        type: "event",
        name: "ValidatorRegistered",
        inputs: [{ type: "address", name: "validator", indexed: true }],
        anonymous: false,
    },
    {
        type: "event",
        name: "ValidatorDeregistered",
        inputs: [{ type: "address", name: "validator", indexed: true }],
        anonymous: false,
    },
    {
        type: "event",
        name: "ValidatorAffiliated",
        inputs: [
            { type: "address", name: "validator", indexed: true },
            { type: "address", name: "group", indexed: true },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ValidatorDeaffiliated",
        inputs: [
            { type: "address", name: "validator", indexed: true },
            { type: "address", name: "group", indexed: true },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ValidatorEcdsaPublicKeyUpdated",
        inputs: [
            { type: "address", name: "validator", indexed: true },
            { type: "bytes", name: "ecdsaPublicKey", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ValidatorBlsPublicKeyUpdated",
        inputs: [
            { type: "address", name: "validator", indexed: true },
            { type: "bytes", name: "blsPublicKey", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ValidatorScoreUpdated",
        inputs: [
            { type: "address", name: "validator", indexed: true },
            { type: "uint256", name: "score", indexed: false },
            { type: "uint256", name: "epochScore", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ValidatorGroupRegistered",
        inputs: [
            { type: "address", name: "group", indexed: true },
            { type: "uint256", name: "commission", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ValidatorGroupDeregistered",
        inputs: [{ type: "address", name: "group", indexed: true }],
        anonymous: false,
    },
    {
        type: "event",
        name: "ValidatorGroupMemberAdded",
        inputs: [
            { type: "address", name: "group", indexed: true },
            { type: "address", name: "validator", indexed: true },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ValidatorGroupMemberRemoved",
        inputs: [
            { type: "address", name: "group", indexed: true },
            { type: "address", name: "validator", indexed: true },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ValidatorGroupMemberReordered",
        inputs: [
            { type: "address", name: "group", indexed: true },
            { type: "address", name: "validator", indexed: true },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ValidatorGroupCommissionUpdateQueued",
        inputs: [
            { type: "address", name: "group", indexed: true },
            { type: "uint256", name: "commission", indexed: false },
            { type: "uint256", name: "activationBlock", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ValidatorGroupCommissionUpdated",
        inputs: [
            { type: "address", name: "group", indexed: true },
            { type: "uint256", name: "commission", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ValidatorEpochPaymentDistributed",
        inputs: [
            { type: "address", name: "validator", indexed: true },
            { type: "uint256", name: "validatorPayment", indexed: false },
            { type: "address", name: "group", indexed: true },
            { type: "uint256", name: "groupPayment", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RegistrySet",
        inputs: [{ type: "address", name: "registryAddress", indexed: true }],
        anonymous: false,
    },
    {
        type: "event",
        name: "OwnershipTransferred",
        inputs: [
            { type: "address", name: "previousOwner", indexed: true },
            { type: "address", name: "newOwner", indexed: true },
        ],
        anonymous: false,
    },
];