# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Meteor
      run: /usr/local/bin/meteor npm install
    - name: Build application
      run: /usr/local/bin/meteor build ../big-dipper-bundle/ --directory --architecture os.linux.x86_64 --server-only
    - name: Install Dependencies
      working-directory: ../big-dipper-bundle/bundle/programs/server
      run: npm install --production
    - name: Save Enviroment Variables
      working-directory: ../big-dipper-bundle/bundle
      run: |
        touch .env
        echo APP_TYPE=${{secrets.APP_TYPE}} >> .env
        echo STARTUP_FILE=${{secrets.STARTUP_FILE}} >> .env
        echo MONGO_URL=${{secrets.MONGO_URL}} >> .env
        echo ROOT_URL=${{secrets.ROOT_URL}} >> .env
        echo METEOR_SETTINGS=${{secrets.METEOR_SETTINGS}} >> .env
        echo NODE_TLS_REJECT_UNAUTHORIZED=${{secrets.NODE_TLS_REJECT_UNAUTHORIZED}} >> .env
        echo NODE_OPTIONS=${{secrets.NODE_OPTIONS}} >> .env
        echo TOOL_NODE_FLAGS=${{secrets.TOOL_NODE_FLAGS}} >> .env
        echo LOG_FILE=${{secrets.LOG_FILE}} >> .env
        echo PID_FILE=${{secrets.PID_FILE}} >> .env
        echo ENVIRONMENT=${{secrets.ENVIRONMENT}} >> .env
        echo PORT=${{secrets.PORT}} >> .env
        echo DAEMONIZE=${{secrets.DAEMONIZE}} >> .env
        echo USER=${{secrets.USER}} >> .env
        cat .env
    - name: Add Passenger file
      working-directory: ../big-dipper-bundle/bundle
      run: |
        cp ~/Passengerfile.json .  
        cat Passengerfile.json
    - name: Restart the passenger
      working-directory: ../big-dipper-bundle/bundle
      run: |
        sudo /usr/bin/passenger stop
        sudo /usr/bin/passenger start
        npm test
