# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Meteor
      working-directory: ../big-dipper-bundle/bundle
      run: /usr/local/bin/meteor npm install
    - name: Build application
      run: /usr/local/bin/meteor build ../big-dipper-bundle/ --directory --architecture os.linux.x86_64 --server-only
    - name: Install Dependencies
      working-directory: ../big-dipper-bundle/bundle/programs/server
      run: npm install --production
    - name: Add Passenger file
      working-directory: ../big-dipper-bundle/bundle
      run: |
        touch Passengerfile.json
        echo ${{secrets.APP_TYPE}} >> Passengerfile.json
        echo ${{secrets.STARTUP_FILE}} >> Passengerfile.json
        echo ${{secrets.MONGO_URL}} >> Passengerfile.json
        echo ${{secrets.ROOT_URL}} >> Passengerfile.json
        echo ${{secrets.METEOR_SETTINGS}} >> Passengerfile.json
        echo ${{secrets.NODE_TLS_REJECT_UNAUTHORIZED}} >> Passengerfile.json
        echo ${{secrets.NODE_OPTIONS}} >> Passengerfile.json
        echo ${{secrets.TOOL_NODE_FLAGS}} >> Passengerfile.json
        echo ${{secrets.LOG_FILE}} >> Passengerfile.json
        echo ${{secrets.PID_FILE}} >> Passengerfile.json
        echo ${{secrets.ENVIRONMENT}} >> Passengerfile.json
        echo ${{secrets.PORT}} >> Passengerfile.json
        echo ${{secrets.DAEMONIZE}} >> Passengerfile.json
        echo ${{secrets.USER}} >> Passengerfile.json
        cat Passengerfile.json
    - name: Restart the passenger
      working-directory: ../big-dipper-bundle/bundle
      run: |
        sudo /usr/bin/passenger stop
        sudo /usr/bin/passenger start
        npm test
