# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Meteor
      run: |
          curl https://install.meteor.com/ | sh
          meteor npm install
    - name: Build application
      run: meteor build ../big-dipper-bundle/ --directory --architecture os.linux.x86_64 --server-only
    - name: Install Dependencies
      working-directory: ../big-dipper-bundle/bundle/programs/server
      run: npm install --production
    - name: Add Passenger file
      working-directory: ../big-dipper-bundle/bundle
      run: |
        touch Passenger.json
        echo ${{secrets.PASSENGER}} >> Passenger.json
    - name: Restart the passenger
      working-directory: ../big-dipper-bundle/bundle
      run: |
        sudo passenger stop
        sudo passenger start
        npm test
